
import React from 'react';
import { useNavigate } from 'react-router-dom';

const MFA: React.FC = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-midnight flex items-center justify-center font-display relative overflow-hidden">
      <div className="absolute inset-0 bg-grid-pattern opacity-10 pointer-events-none" />
      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 size-[600px] bg-primary/10 blur-[120px] rounded-full pointer-events-none" />

      <div className="w-full max-w-[480px] px-6 relative z-10">
        <div className="bg-navy/70 border border-white/10 backdrop-blur-2xl rounded-3xl p-12 flex flex-col items-center gap-10 shadow-2xl">
          <div className="flex flex-col items-center gap-6">
             <div className="size-16 rounded-full bg-primary/20 flex items-center justify-center text-primary border border-primary/30 relative">
               <span className="material-symbols-outlined !text-4xl">lock_person</span>
               <div className="absolute -top-1 -right-1 size-3 rounded-full bg-primary animate-ping" />
             </div>
             <div className="text-center">
               <h1 className="text-white text-2xl font-bold tracking-tight">Two-Factor Authentication</h1>
               <p className="text-slate-400 text-sm mt-3 leading-relaxed px-4">
                 Enter the 6-digit code generated by your authenticator app for the account ending in <span className="text-white font-bold">**89</span>.
               </p>
             </div>
          </div>

          <div className="w-full flex justify-center gap-3">
             {[1, 2, 3, 4, 5, 6].map(i => (
               <div key={i} className="size-14 rounded-xl bg-midnight/80 border border-card-border flex items-center justify-center relative group">
                  {i === 1 && <div className="h-6 w-px bg-primary animate-pulse" />}
                  <div className="absolute bottom-0 left-2 right-2 h-0.5 bg-card-border group-hover:bg-primary transition-all" />
               </div>
             ))}
          </div>

          <div className="w-full flex items-center justify-between text-xs font-bold uppercase tracking-widest">
            <div className="flex items-center gap-2 text-slate-500">
               <span className="material-symbols-outlined !text-sm">timer</span>
               Resend code in <span className="text-primary font-mono">00:24</span>
            </div>
            <button className="text-slate-500 hover:text-white transition-colors">Resend now</button>
          </div>

          <button onClick={() => navigate('/mission')} className="w-full h-14 bg-primary hover:bg-blue-600 text-white font-bold rounded-xl shadow-neon-blue transition-all uppercase tracking-widest flex items-center justify-center gap-3 group">
            Verify Identity
            <span className="material-symbols-outlined !text-lg transition-transform group-hover:translate-x-1">arrow_forward</span>
          </button>

          <div className="w-full pt-8 border-t border-white/5 flex flex-col items-center gap-6">
             <button className="text-slate-500 hover:text-white text-xs font-bold uppercase tracking-widest transition-colors flex items-center gap-3">
                <span className="material-symbols-outlined !text-lg">key</span>
                Use backup recovery key
             </button>
             <div className="text-center space-y-1">
               <p className="text-[10px] text-slate-600 uppercase tracking-widest">Secure 256-bit encrypted connection</p>
               <p className="text-[10px] text-slate-600 uppercase tracking-widest">Protected by NYDev Shield™ AI</p>
             </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default MFA;
